#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
     path: /api/login_check

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

#delete_avatar:
#   path: 'api/user_avatars/{id}'
#   methods: ['DELETE']
#   defaults:
#       _controller: '\App\Controller\UserAvatarController::deleteAvatar'
#        _api_resource_class: 'App\Entity\Media\UserAvatar'
#       _api_item_operation_name: 'deleteAvatar'